### ISSUE TITLE
Why did you fork?

### ISSUE THREAD

**Issue by matepek** [AnakinMac/vscode-catch2-test-adapter#1]
Hey,
I've noticed your fork and your changes.
I would like to understand the use-case, the reason why you modified the adapter.

My guess is that the "google-test-listing" took too much time in your case and you are doing some caching. Am I right? Would you tell me more about it? Maybe other users could profit about some solution.

Also, you changed the testRe to accept test names starting with digits.
I thought it is not possible to start with a digit, because:
- "[Both names must be valid C++ identifiers](https://github.com/google/googletest/blob/master/googletest/docs/primer.md#simple-tests)"
- and "[A valid identifier must begin with a non-digit character](https://en.cppreference.com/w/cpp/language/identifiers)"

But actually it is working, so I will add it.

**Comment by AnakinMac** [comment]
I forked due to several issues I noticed, If things works fine I will push it back to upstream.
1. Slow test listing, yes. We have several workspaces have around 4k unit/pkg test points. Listing takes around 5 minutes every time I reopen the VSCode, which is annoying.
2. Test points start with digits, yup, I aware of google's documentation, but seems it not enforced, so we do have people doing that...That's why I haven't opened an issue...

Also, new to TypeScript, I'm having fun. :)

**Comment by matepek** [comment]
Would you do me a favour? 

Could you measure the duration of test-loading with a bash script like:
```
find . -name "gtest*" -exec "{}" --gtest_list_tests ";"
```

In case you are using windows you can use Git Bash for it. (hopefully)

**Comment by AnakinMac** [comment]
Tweak the script a little bit
time find . -name "*test" -exec "{}" --gtest_list_tests ";"
8.00 real         6.97 user         0.91 sys

Also ran the following:
find . -name "*test" | wc -l
21
find . -name "*test" -exec "{}" --gtest_list_tests ";" | wc -l                                                                                                                                                                     
7219

**Comment by AnakinMac** [comment]
That is only one folder, usually I'll have another 3 or 4.

**Comment by matepek** [comment]
Nice, ty.
Is that mean 8 sec?

**Comment by AnakinMac** [comment]
Yes. I think the bottleneck might be building the tree view?

**Comment by matepek** [comment]
I guess. 

But is your modification actually helped? How much?

Anyway, I will modify the adapter to run some loading tasks parallel.

**Comment by AnakinMac** [comment]
I haven't timed that, it feels like a little bit, not very well.

BTW:
Any plan to fix this issue?
https://github.com/Microsoft/vscode/issues/70125

**Comment by AnakinMac** [comment]
I hacked around it. But not sure it's the right fix.

**Comment by matepek** [comment]
I haven't noticed this bug. I'm on it.

Meanwhile, would you like to install a custom build of my adapter and trying out the performance of it?

**Comment by AnakinMac** [comment]
Sure.

**Comment by matepek** [comment]
[vscode-catch2-test-adapter-2.3.24-dev.zip](https://github.com/AnakinMac/vscode-catch2-test-adapter/files/2967716/vscode-catch2-test-adapter-2.3.24-dev.zip)

I'm curious that it helps a bit or not.

**Comment by AnakinMac** [comment]
Feels way faster now.

2 things remaining:
testname starts with number and unable to start debug session..

**Comment by AnakinMac** [comment]
my bad, test name starts with number works 👍

**Comment by matepek** [comment]
Is it fast enough or do you think more optimization/caching would be nice?

**Comment by AnakinMac** [comment]
Once you release it I can merge with my caching hack and see how much it can improve.

**Comment by matepek** [comment]
Released.

I also created a workspace with 300 executable (865 tests/executable).
It took around 10 seconds to create the xml files. (But these are lightweight exec, without robust static objects.)
The new version of the extension loads them around 30 seconds.

 I added a new config as an experimental feature. I'm looking forward of your experiences.
`catch2TestExplorer.enableTestListCaching`

I personally don't really feel the difference.
I have an idea for another approach, but that is a bit bigger development so, please try out this, and we will see that do we really need that or not.

**Comment by AnakinMac** [comment]
Cool, let me try it.

**Comment by AnakinMac** [comment]
Another enhancement idea.

When click the reload button, it is possible to only reload changed tests?
This is especially useful for multi-root workspace.
Each workspace will have it's own unit/pkg tests.
FolderA/unittest
FolderA/pkgtest
FolderB/unittest
...

When I add a new test point to folder A's unit test, I have to reload everything, that is really annoy.

**Comment by matepek** [comment]
1. If you add a new file which matches the pattern, then that should be recognised and added automatically.

2. If you add a new test to an exiting executable (so basically recompiling it) that should be recognised and refreshed automatically too.

3. Even if there are somehow it is not recognised and you just rerun all the tests in the executable with the executable's play button it should recognise the change and reload only that one.

So I would preserve the reload button as a "hard reload" option.

Does 1-3 works for you properly? Aren't those features good enough? (Explain it please.)

PS.: Multi-root environment shouldn't be a problem.

**Comment by AnakinMac** [comment]
1 and 2 does not work.

3 works.

**Comment by matepek** [comment]
That is not good.
I cannot reproduce it.

If you would try to debug it: Put a breakpoint into TestExecutableInfo.ts -> _handleEverything then touch and create an executable.
That would be tell something about the watcher.

**Comment by AnakinMac** [comment]
ok, I'll try it!

**Comment by AnakinMac** [comment]
Figured out what happened, see my last commit.

**Comment by matepek** [comment]
Ah, I forgot to mention that case. It is only working inside the workspace folder.

The earlier version were using this kind of watching before I changed to the current resource friendly solution.

Before I consider supporting again this case, let’s talk about your project structure a bit:
Projects usually have a ‘build’ or ‘out’ folder inside the project’s root directory. Why do you have test files outside?

**Comment by AnakinMac** [comment]
We are using a mono repository (~1m files, 100GB). 
So usually things I added to VSCode is a tiny fraction of it.

The structure looks like this
Root
  |-- build/<platform>/test/module...
  |-- src/<modules>/...

Only src/moduleA/... is added to VSCode.

**Comment by matepek** [comment]
Uh, okay, I can see why you don't want to add the whole root.

I guess you are not using glob pattern for those executables but you list all of them explicitly. Am I right?

**Comment by AnakinMac** [comment]
right

**Comment by matepek** [comment]
Added chokidar to the project. Released.

It supports glob pattern, but currently i would say it is an experimental feature.
My concern is that now my extension's size is 10 times bigger. :S
Will see...

Any feedback is welcome.

**Comment by AnakinMac** [comment]
Noticed that as well.
I tried Node.js's file watcher first, that seems not working very well on mac. Maybe there are some other libraries.

**Comment by AnakinMac** [comment]
Another question! Is there any settings to set all unit/pkg test autorun?

**Comment by matepek** [comment]
Yes, there is. Next to the reload icon there is a '...' icon -> Enable autorun.
Or right click on the test or suite -> Enable autorun.

Also this can be helpful: https://github.com/hbenl/vscode-test-explorer#commands

**Comment by AnakinMac** [comment]
Is there any programable way to do this? Like in settings.json?

**Comment by AnakinMac** [comment]
Is there any programable way? Like something in settings.json. Feels like an enhancement to test explorer.

**Comment by matepek** [comment]
Oh, I see, you wanna set this option as default.

I have no API endpoints to do it. I suggest to create a feature request here:  https://github.com/hbenl/vscode-test-explorer

**Comment by AnakinMac** [comment]
Done.
https://github.com/hbenl/vscode-test-explorer/issues/51

**Comment by matepek** [comment]
Hey there.

I opened an [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/84) about this feature. I would be pleased if you could share your experience there about the feature.
